### ISSUE TITLE
Distinguish between inbound and outbound STARTTLS support #26

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-backend#104]
Migrated from EFForg/starttls-everywhere#71

Migrated from starttls-check, opened by @sydneyli on 7/13

**Comment by sydneyli** [comment]
I don't think we should do this. we should focus on inbound STARTTLS support, as that's what the policy list is for.
We could suggest a tool on the website, like the OP of the original issue said: 
> It would be great if there were a tool to check outbound support, or at least some reference to this configuration issue in the faq, with a link to a tool such as checktls.com/TestSender.

So I've created EFForg/starttls-frontend#221 to track progress on that front.
