### ISSUE TITLE
Check STARTTLS command discrepancy between websites

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-backend#107]
[starttls-everywhere.org](https://starttls-everywhere.org/) says that the bigpond.com and telstra.com mailbox - extmail.bigpond.com - 'does not support STARTTLS'. [TestReceiver](https://www.checktls.com/perl/live/TestReceiver.pl) and [TestSender](https://www.checktls.com/perl/live/TestSender.pl) on www.checktls.com reports that 'STARTTLS command works on this server' when a @bigpond.com address was tested. 

---

Migrated from starttls-check, opened by @Jawshy on 8/3

**Comment by sydneyli** [comment]
So the reason for this is that Go's library assumes that the first banner is the greeting banner (and [removes it](https://golang.org/src/net/smtp/smtp.go?s=10558:10611#L137) before parsing the rest of the extension banners), but this particular mailserver has the STARTTLS banner as the first one.

**Comment by sydneyli** [comment]
According to [RFC5321](https://tools.ietf.org/html/rfc5321#section-4.1.1.1) this behavior is correct. Closing.
