### ISSUE TITLE
Migrate to an ORM?

### ISSUE THREAD

**Issue by sydneyli** [EFForg/starttls-backend#132]
as discussed with @vbrown608, maybe we want to do this before #130 ! :)

https://github.com/jinzhu/gorm seems like a popular option.

**Comment by sydneyli** [comment]
Dumping some more less-than-GORM-but-more-than-what-we-have-right-now options.
 * Barbones SQL + something like https://godoc.org/gopkg.in/gorp.v2
 * Set of extensions to native `sql` package: https://github.com/jmoiron/sqlx and https://github.com/gocraft/dbr

**Comment by vbrown608** [comment]
Closing for now - this may be useful in the future, but our current database approach works for now.
