### ISSUE TITLE
Clarify new scan DB schema and migrate

### ISSUE THREAD

**Issue by sydneyli** [EFForg/starttls-backend#140]
Depends on #132, a part of #131
```
policy_scan
  * date, domain, domain_id, hostname_scan_ids, mx_success, mx_failure_msg, success

hostname_scan
  * date, hostname, success, failure_msg

hostname_settings
  * hostname, wait_duration (cache settings)
```
Plus, we should migrate the scan database itself to store data in a more structured manner.

**Comment by sydneyli** [comment]
Now that #150 has landed, we want to consolidate all the duplicated stored scans.

**Comment by vbrown608** [comment]
Closing for now - duplicated stored scans aren't causing problems they simplify database interactions.
