### ISSUE TITLE
Rate limiting error should surface more clearly

### ISSUE THREAD

**Issue by sydneyli** [EFForg/starttls-backend#167]
Also let's raise the rate-limit :)

**Comment by sydneyli** [comment]
Also: we want to fix the error code to be "Exceeded Rate Limit". once that happens i think we can close this ticket

**Comment by vbrown608** [comment]
I don't think there's a status like that. We're sending 429 "Too Many Requests".

**Comment by sydneyli** [comment]
This is fixed!
